# Generated by Django 5.0.7 on 2024-07-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_revendeur_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='revendeur',
        ),
    ]
