# Generated by Django 5.0.7 on 2024-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_delete_revendeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_adsl_client', models.CharField(max_length=20)),
                ('mois', models.CharField(max_length=20)),
                ('annee', models.IntegerField()),
                ('numero_facture', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField()),
                ('date_fin_paiement', models.DateTimeField()),
                ('montant_facture', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_debut_facture', models.DateTimeField()),
                ('date_fin_facture', models.DateTimeField()),
            ],
        ),
    ]
