# Generated by Django 5.0.7 on 2024-08-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='abonnement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='identifiant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
