# Generated by Django 5.0.7 on 2024-10-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_facture_abonnement_facture_identifiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='proprietaire_cheque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
